version: '3'

services:
  core:
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      - MYSQL_USE=core
      - MYSQL_PASSWORD=core
      - MYSQL_DATABASE=core
      - MYSQL_ROOT_PASSWORD=root
  tenant:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USE=tenant
      - MYSQL_PASSWORD=tenant
      - MYSQL_DATABASE=tenant
      - MYSQL_ROOT_PASSWORD=root
