name: Docker Image CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy env's
        run: |
          find ./packages/antify-admin/src/ -type f -name ".env.dist" | while read fname; do
            dirname=`dirname "$fname"`
            foldername=`basename "$dirname"`
            filename=`basename "$fname"`
            newname=`echo "$dirname" | sed -e "s/ /_/g"`
            cp "${dirname}/$filename" "./packages/antify-admin/src/.env"
          done
      # - name: Build the Docker image
      #   run: docker compose build
      # - name: How am I?
      #   run: docker ps -a
      # - name: Tag Docker container
      #   run: docker tag antify-admin ghcr.io/antify/antify-admin:latest
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
